export const DEFAULT = "DEFAULT"

export const SELECT_ACTIVE = "SELECT_ACTIVE"
export const UPDATE_CHAT = "UPDATE_CHAT"
export const UPDATE_CHAT_TYPING = "UPDATE_CHAT_TYPING"

export const UPDATE_USERID = "UPDATE_USERID"

export const UPDATE_CHAT_LIST = "UPDATE_CHAT_LIST"